[profile.default]
src = 'src'
# test = 'tests'
test = 'certora/harness'
#test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{access = "write", path = "./reports"}]

[rpc_endpoints]
avalanche = "https://rpc.ankr.com/avalanche"
polygon = "https://rpc.ankr.com/polygon"
